SIGN_UP_EMAIL_EXISTS = 'EMAIL_EXISTS'
SIGN_UP_EMAIL_VALID = 'EMAIL_NOT_VALID'
SIGN_UP_PASSWORD = 'WEAK_PASSWORD'
SIGN_UP_USER = 'INVALID_USERNAME'
SIGN_UP_USERNAME_SHORT = 'USERNAME_TOO_SHORT'
SIGN_UP_USERNAME_EXISTS = 'USERNAME_EXISTS'

SIGN_IN_EMAIL = 'EMAIL_NOT_FOUND'
SIGN_IN_PASSWORD = 'INVALID_PASSWORD'
